export const developers = [
  {
    id: 1,
    name: 'Artem Zakharchuk',
    telegram: 'https://t.me/Artem_Zakharchuk',
    lindedin: 'https://www.linkedin.com/in/artem-zakharchuk-818ba3131',
    github: 'https://github.com/ArtemZakhar',
    email: 'artemzakharchuk@gmail.com',
  },
  {
    id: 2,
    name: 'Taras Samchenko',
    telegram: 'https://t.me/topacsam',
    lindedin: 'https://www.linkedin.com/in/taras-samchenko-71b416208/',
    github: 'https://github.com/tarassamchenko',
    email: '',
  },
  {
    id: 3,
    name: 'Grigorii Kachurovskii',
    telegram: 'https://t.me/grigoriikachurovskii',
    lindedin: 'https://www.linkedin.com/in/grygoryy-kachurovskyy-b4994b283/',
    github: 'https://github.com/GrigoryyKach',
    email: '',
  },
  {
    id: 4,
    name: 'Oleh Tsiolkovskiy',
    telegram: 'https://t.me/OlegTS86',
    lindedin: 'https://www.linkedin.com/in/oleh-tsiolkovskiy-2729692b8/',
    github: 'https://github.com/OTsiolkovskiy',
    email: '',
  },
  {
    id: 5,
    name: 'Oleh Dynys',
    telegram: 'https://t.me/Olek_91',
    lindedin: '',
    github: 'https://github.com/Olek-91',
    email: '',
  },
];
